# Generated by Django 6.0.5 on 2026-05-14 18:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plataforma', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ingrediente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_excel', models.CharField(blank=True, db_index=True, max_length=30, null=True)),
                ('nombre', models.CharField(max_length=220)),
                ('activo', models.BooleanField(default=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'ingrediente',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=180, unique=True)),
                ('activo', models.BooleanField(default=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'proveedor',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='SeccionAlmacen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=80, unique=True)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'seccion_almacen',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='UnidadMedida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clave', models.CharField(max_length=10, unique=True)),
                ('nombre', models.CharField(blank=True, default='', max_length=60)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'unidad_medida',
                'ordering': ['clave'],
            },
        ),
        migrations.CreateModel(
            name='IngredienteProveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('presentacion', models.CharField(blank=True, default='', max_length=160)),
                ('es_principal', models.BooleanField(default=False)),
                ('activo', models.BooleanField(default=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('ingrediente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proveedores', to='plataforma.ingrediente')),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ingredientes', to='plataforma.proveedor')),
            ],
            options={
                'db_table': 'ingrediente_proveedor',
                'ordering': ['ingrediente__nombre', 'proveedor__nombre'],
            },
        ),
        migrations.AddField(
            model_name='ingrediente',
            name='seccion_almacen',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ingredientes', to='plataforma.seccionalmacen'),
        ),
        migrations.AddField(
            model_name='ingrediente',
            name='unidad_compra',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ingredientes', to='plataforma.unidadmedida'),
        ),
        migrations.CreateModel(
            name='PrecioIngredienteProveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio_unitario', models.DecimalField(decimal_places=4, max_digits=12)),
                ('fecha_precio', models.DateField(blank=True, null=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('ingrediente_proveedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='precios', to='plataforma.ingredienteproveedor')),
            ],
            options={
                'db_table': 'precio_ingrediente_proveedor',
                'ordering': ['-fecha_precio', '-creado'],
                'constraints': [models.CheckConstraint(condition=models.Q(('precio_unitario__gte', 0)), name='precio_ingrediente_proveedor_no_negativo')],
            },
        ),
        migrations.AddConstraint(
            model_name='ingredienteproveedor',
            constraint=models.UniqueConstraint(fields=('ingrediente', 'proveedor', 'presentacion'), name='unique_ingrediente_proveedor_presentacion'),
        ),
    ]
