# Generated by Django 6.0.5 on 2026-05-14 18:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plataforma', '0002_ingrediente_proveedor_seccionalmacen_unidadmedida_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaReceta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=80, unique=True)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'categoria_receta',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Receta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_excel', models.CharField(blank=True, db_index=True, max_length=30, null=True)),
                ('nombre', models.CharField(max_length=220)),
                ('activo', models.BooleanField(default=True)),
                ('porciones_base', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('kcal_porcion', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('proteina_g', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('lipidos_g', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('hdc_g', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('notas', models.TextField(blank=True, default='')),
                ('validado_nutri', models.BooleanField(default=False)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('categoria_2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='recetas_secundarias', to='plataforma.categoriareceta')),
                ('categoria_uso', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recetas_uso', to='plataforma.categoriareceta')),
            ],
            options={
                'db_table': 'receta',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='RecetaIngrediente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.DecimalField(decimal_places=4, max_digits=12)),
                ('notas', models.CharField(blank=True, default='', max_length=220)),
                ('activo', models.BooleanField(default=True)),
                ('ingrediente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recetas', to='plataforma.ingrediente')),
                ('receta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredientes', to='plataforma.receta')),
                ('unidad_medida', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recetas_ingredientes', to='plataforma.unidadmedida')),
            ],
            options={
                'db_table': 'receta_ingrediente',
                'ordering': ['receta__nombre', 'ingrediente__nombre'],
                'constraints': [models.CheckConstraint(condition=models.Q(('cantidad__gt', 0)), name='receta_ingrediente_cantidad_positiva')],
            },
        ),
    ]
