# Generated by Django 6.0.5 on 2026-05-14 19:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plataforma', '0003_categoriareceta_receta_recetaingrediente'),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuSemanal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, default='', max_length=120)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('estado', models.CharField(choices=[('BORRADOR', 'Borrador'), ('ACTIVO', 'Activo'), ('CERRADO', 'Cerrado')], default='BORRADOR', max_length=20)),
                ('activo', models.BooleanField(default=True)),
                ('notas', models.TextField(blank=True, default='')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'menu_semanal',
                'ordering': ['-fecha_inicio'],
            },
        ),
        migrations.CreateModel(
            name='MenuSemanalDetalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('dia_semana', models.IntegerField(choices=[(1, 'Lunes'), (2, 'Martes'), (3, 'Miércoles'), (4, 'Jueves'), (5, 'Viernes')])),
                ('pax', models.PositiveIntegerField(default=0)),
                ('sin_servicio', models.BooleanField(default=False)),
                ('texto_original', models.CharField(blank=True, default='', max_length=260)),
                ('notas', models.CharField(blank=True, default='', max_length=260)),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='plataforma.menusemanal')),
                ('tiempo_comida', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='menus_detalle', to='plataforma.categoriareceta')),
            ],
            options={
                'db_table': 'menu_semanal_detalle',
                'ordering': ['fecha', 'tiempo_comida__nombre'],
            },
        ),
        migrations.CreateModel(
            name='MenuSemanalDetalleReceta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orden', models.PositiveIntegerField(default=1)),
                ('texto_original', models.CharField(blank=True, default='', max_length=220)),
                ('detalle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recetas', to='plataforma.menusemanaldetalle')),
                ('receta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='menus_detalle', to='plataforma.receta')),
            ],
            options={
                'db_table': 'menu_semanal_detalle_receta',
                'ordering': ['orden'],
            },
        ),
        migrations.AddConstraint(
            model_name='menusemanaldetalle',
            constraint=models.UniqueConstraint(fields=('menu', 'fecha', 'tiempo_comida'), name='unique_menu_fecha_tiempo_comida'),
        ),
        migrations.AddConstraint(
            model_name='menusemanaldetallereceta',
            constraint=models.UniqueConstraint(fields=('detalle', 'receta', 'orden'), name='unique_menu_detalle_receta_orden'),
        ),
    ]
