# Generated by Django 6.0.5 on 2026-05-14 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plataforma', '0004_menusemanal_menusemanaldetalle_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SeccionSistema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clave', models.CharField(max_length=60, unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'seccion_sistema',
                'ordering': ['nombre'],
            },
        ),
        migrations.AddField(
            model_name='usuario',
            name='imagen',
            field=models.ImageField(blank=True, max_length=160, null=True, upload_to='usuarios/'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='secciones_acceso',
            field=models.ManyToManyField(blank=True, related_name='usuarios', to='plataforma.seccionsistema'),
        ),
    ]
