# Generated by Django 6.0.5 on 2026-05-27 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plataforma', '0006_seed_secciones_sistema'),
    ]

    operations = [
        migrations.AddField(
            model_name='proveedor',
            name='anticipacion_dias',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='categorias',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='codigo_excel',
            field=models.CharField(blank=True, db_index=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='contacto',
            field=models.CharField(blank=True, default='', max_length=180),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='dias_entrega',
            field=models.CharField(blank=True, default='', max_length=220),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='email',
            field=models.EmailField(blank=True, default='', max_length=180),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='metodo_pedido',
            field=models.CharField(blank=True, default='', max_length=80),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='whatsapp',
            field=models.CharField(blank=True, default='', max_length=80),
        ),
    ]
