# Generated by Django 6.0.5 on 2026-05-27 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plataforma', '0007_proveedor_anticipacion_dias_proveedor_categorias_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaProveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=80, unique=True)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'categoria_proveedor',
                'ordering': ['nombre'],
            },
        ),
        migrations.AddField(
            model_name='proveedor',
            name='categorias_proveedor',
            field=models.ManyToManyField(blank=True, related_name='proveedores', to='plataforma.categoriaproveedor'),
        ),
    ]
