# Generated by Django 6.0.5 on 2026-05-27 21:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plataforma', '0010_seed_grupos_calendario_section'),
    ]

    operations = [
        migrations.CreateModel(
            name='NivelGrupo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=80, unique=True)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'nivel_grupo',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='TiempoComida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clave', models.CharField(max_length=30, unique=True)),
                ('nombre', models.CharField(max_length=80)),
                ('orden', models.PositiveSmallIntegerField(default=1)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'tiempo_comida',
                'ordering': ['orden', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='PeriodoGrupo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('activo', models.BooleanField(default=True)),
                ('notas', models.TextField(blank=True, default='')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'periodo_grupo',
                'ordering': ['-fecha_inicio'],
                'constraints': [models.CheckConstraint(condition=models.Q(('fecha_fin__gte', models.F('fecha_inicio'))), name='periodo_grupo_fechas_validas')],
            },
        ),
        migrations.CreateModel(
            name='GrupoComensales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('alumnos', models.PositiveIntegerField(default=0)),
                ('activo', models.BooleanField(default=True)),
                ('nivel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='grupos', to='plataforma.nivelgrupo')),
                ('periodo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grupos', to='plataforma.periodogrupo')),
            ],
            options={
                'db_table': 'grupo_comensales',
                'ordering': ['periodo__fecha_inicio', 'nivel__nombre', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='PaxTiempoComida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pax_calculado', models.PositiveIntegerField(default=0)),
                ('pax_confirmado', models.PositiveIntegerField(blank=True, null=True)),
                ('notas', models.TextField(blank=True, default='')),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('periodo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pax_tiempos', to='plataforma.periodogrupo')),
                ('tiempo_comida', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pax_periodos', to='plataforma.tiempocomida')),
            ],
            options={
                'db_table': 'pax_tiempo_comida',
                'ordering': ['periodo__fecha_inicio', 'tiempo_comida__orden'],
            },
        ),
        migrations.CreateModel(
            name='GrupoTiempoComida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aplica', models.BooleanField(default=True)),
                ('pax_override', models.PositiveIntegerField(blank=True, null=True)),
                ('grupo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tiempos_comida', to='plataforma.grupocomensales')),
                ('tiempo_comida', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='grupos', to='plataforma.tiempocomida')),
            ],
            options={
                'db_table': 'grupo_tiempo_comida',
                'ordering': ['grupo__nombre', 'tiempo_comida__orden'],
            },
        ),
        migrations.AddConstraint(
            model_name='grupocomensales',
            constraint=models.UniqueConstraint(fields=('periodo', 'nombre'), name='unique_grupo_comensales_periodo_nombre'),
        ),
        migrations.AddConstraint(
            model_name='paxtiempocomida',
            constraint=models.UniqueConstraint(fields=('periodo', 'tiempo_comida'), name='unique_pax_tiempo_comida_periodo'),
        ),
        migrations.AddConstraint(
            model_name='grupotiempocomida',
            constraint=models.UniqueConstraint(fields=('grupo', 'tiempo_comida'), name='unique_grupo_tiempo_comida'),
        ),
    ]
