# Generated by Django 6.0.5 on 2026-05-27 21:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plataforma', '0012_seed_grupos_calendario_catalogs'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecepcionInsumo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('folio', models.CharField(blank=True, default='', max_length=40)),
                ('fecha', models.DateField()),
                ('notas', models.TextField(blank=True, default='')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('proveedor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='recepciones', to='plataforma.proveedor')),
            ],
            options={
                'db_table': 'recepcion_insumo',
                'ordering': ['-fecha', '-creado'],
            },
        ),
        migrations.CreateModel(
            name='RecepcionInsumoDetalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.DecimalField(decimal_places=4, max_digits=12)),
                ('precio_unitario', models.DecimalField(decimal_places=4, max_digits=12)),
                ('notas', models.CharField(blank=True, default='', max_length=220)),
                ('ingrediente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recepciones', to='plataforma.ingrediente')),
                ('recepcion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='plataforma.recepcioninsumo')),
                ('unidad_medida', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recepciones_insumo', to='plataforma.unidadmedida')),
            ],
            options={
                'db_table': 'recepcion_insumo_detalle',
                'ordering': ['ingrediente__nombre'],
                'constraints': [models.CheckConstraint(condition=models.Q(('cantidad__gt', 0)), name='recepcion_insumo_detalle_cantidad_positiva'), models.CheckConstraint(condition=models.Q(('precio_unitario__gte', 0)), name='recepcion_insumo_detalle_precio_no_negativo')],
            },
        ),
    ]
