# Generated by Django 6.0.5 on 2026-05-28 09:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plataforma', '0014_seed_recepcion_insumos_section'),
    ]

    operations = [
        migrations.CreateModel(
            name='MovimientoInventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('ENTRADA_RECEPCION', 'Entrada por recepción')], default='ENTRADA_RECEPCION', max_length=30)),
                ('fecha', models.DateField()),
                ('cantidad', models.DecimalField(decimal_places=4, max_digits=12)),
                ('precio_unitario', models.DecimalField(decimal_places=4, default=0, max_digits=12)),
                ('notas', models.CharField(blank=True, default='', max_length=220)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('ingrediente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimientos_inventario', to='plataforma.ingrediente')),
                ('recepcion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='movimientos_inventario', to='plataforma.recepcioninsumo')),
                ('recepcion_detalle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='movimientos_inventario', to='plataforma.recepcioninsumodetalle')),
                ('unidad_medida', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimientos_inventario', to='plataforma.unidadmedida')),
            ],
            options={
                'db_table': 'movimiento_inventario',
                'ordering': ['-fecha', '-creado'],
            },
        ),
        migrations.CreateModel(
            name='InventarioInsumo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_actual', models.DecimalField(decimal_places=4, default=0, max_digits=14)),
                ('valor_total', models.DecimalField(decimal_places=4, default=0, max_digits=14)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('ingrediente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventarios', to='plataforma.ingrediente')),
                ('unidad_medida', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inventarios_insumo', to='plataforma.unidadmedida')),
            ],
            options={
                'db_table': 'inventario_insumo',
                'ordering': ['ingrediente__nombre'],
                'constraints': [models.UniqueConstraint(fields=('ingrediente', 'unidad_medida'), name='unique_inventario_insumo_unidad')],
            },
        ),
    ]
