# Generated by Django 6.0.5 on 2026-05-28 09:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plataforma', '0016_seed_inventario_section'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimientoinventario',
            name='tipo',
            field=models.CharField(choices=[('ENTRADA_RECEPCION', 'Entrada por recepción'), ('ENTRADA_REINTEGRO_MERMA', 'Entrada por reintegro de merma')], default='ENTRADA_RECEPCION', max_length=30),
        ),
        migrations.CreateModel(
            name='Merma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('tipo', models.CharField(choices=[('INGREDIENTE', 'Ingrediente'), ('RECETA', 'Receta')], max_length=20)),
                ('cantidad', models.DecimalField(decimal_places=4, max_digits=12)),
                ('regresa_inventario', models.BooleanField(default=False)),
                ('motivo', models.CharField(blank=True, default='', max_length=180)),
                ('notas', models.TextField(blank=True, default='')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('ingrediente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='mermas', to='plataforma.ingrediente')),
                ('receta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='mermas', to='plataforma.receta')),
                ('unidad_medida', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='mermas', to='plataforma.unidadmedida')),
            ],
            options={
                'db_table': 'merma',
                'ordering': ['-fecha', '-creado'],
            },
        ),
        migrations.AddField(
            model_name='movimientoinventario',
            name='merma',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='movimientos_inventario', to='plataforma.merma'),
        ),
        migrations.AddConstraint(
            model_name='merma',
            constraint=models.CheckConstraint(condition=models.Q(('cantidad__gt', 0)), name='merma_cantidad_positiva'),
        ),
    ]
